version: "2"
services:

  frontend:
    image: FRONTEND_IMAGE_PLACEHOLDER
    volumes:
      - frontend:/var/lib/vite
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
    ports:
      - "FRONTEND_PORT_PLACEHOLDER:8600"  # Placeholders for port numbers
    networks:
      - nginxproxy_default

  node-scheduler:
    image: NODE_SCHEDULER_IMAGE_PLACEHOLDER
    container_name: node-scheduler
    volumes:
      - sched_data:/var/lib/node-scheduler
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
    ports:
      - "BACKEND_PORT_PLACEHOLDER:3200"  # Placeholders for port numbers
    networks:
      - default

volumes:
  frontend:
  sched_data:

networks:
  nginxproxy_default:
    external:
      name: nginxproxy_default
